language: php
sudo: false

php:
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
